name: kotlin
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd kotlin/sample
          kotlinc App.kt -include-runtime -d App.jar
          java -jar App.jar