name: ant
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo-win.git .
      - run: |
          ant -version
          ant -buildfile ant/build.xml