name: chrome-driver
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo-win.git .
      - run: |
          cd chrome-driver
          pip3 install selenium
          python python-test.py
      - run: |
          cd chrome-driver/java
          mvn install