name: chrome-driver
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd chrome-driver
          pip3 install selenium
          python python-test.py
      - run: |
          cd chrome-driver/java
          mvn install