
name: cmake
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo-win.git .
      - run: |
          which cmake
          cmake --version
      - run: |
          cd cmake/testfiles
          cmake -DCMAKE_SHELL=false -DTEST_ONE="one;two" -DTEST_TWO=/one/two/three -DTEST_WIN_VARIABLE=test -DTEST_VARIABLE=test
      - run: |
          cd cmake/testfiles
          cmake -DCMAKE_SHELL=true -DTEST_ONE="one;two" -DTEST_TWO=/one/two/three -DTEST_VARIABLE=$USER -DTEST_WIN_VARIABLE=%OS%
        shell: cmd