name: docker
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo-win.git .
      - run: docker login
      - run: |
          docker pull mcr.microsoft.com/windows/servercore/insider:10.0.20348.1
          docker run mcr.microsoft.com/windows/servercore/insider:10.0.20348.1
      - run: |
          git clone https://github.com/dockersamples/node-bulletin-board
          cd node-bulletin-board/bulletin-board-app
          docker build --tag bulletinboard:1.0 .
          docker run --publish 8000:8080 --detach --name bb bulletinboard:1.0
          docker rm --force bb
      - run: |
          git clone https://github.com/dockersamples/example-voting-app
          cd example-voting-app
          docker-compose up --build &
          sleep 200
          docker-compose down