name: go
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd go/go-web-app
          go get -d
        shell: pwsh
      - run: |
          cd go/go-web-app
          go build
        shell: pwsh