name: node
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd node/node-typescript
          npm install 
      - run: |
          cd node/node-typescript
          npm test -- --reporter mocha-junit-reporter
