name: node
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/maxim-lobanov/runner-test-repo-win.git .
      - run: |
          cd node/node-typescript
          npm install 
      - run: |
          cd node/node-typescript
          npm test -- --reporter mocha-junit-reporter
