name: openssl
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo some_value > input.txt
      - run: |
          openssl dgst -sha256 -hex input.txt > sha256.txt
      - run: |
          cat sha256.txt