name: powershell
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: Write-Host hello
        shell: pwsh
      - run: ./powershell/scripts/hello.ps1
        shell: pwsh