name: rust
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd rust/src
          rustc hello.rs
          ./hello
        shell: pwsh
      - run: |
          rustup install nightly
          rustup show
        shell: pwsh
      - run: |
          rust/scripts/cargo.ps1
        shell: pwsh