name: wdk
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd windows-driver-kit/winkerneltest
          dotnet restore winkerneltest.sln
          msbuild winkerneltest.sln /p:platform="x64" /p:configuration="release"
