name: wdk
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/bbq-beets/asviridenko-test-repo.git .
      - run: |
          cd windows-driver-kit/winkerneltest
          dotnet restore winkerneltest.sln
          msbuild winkerneltest.sln /p:platform="x64" /p:configuration="release"
