name: xamarin-android
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd xamarin-android/vs2019
          nuget restore XamarinAndroidVS2019.sln
          pwd
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "XamarinAndroidVS2019\XamarinAndroidVS2019.csproj" /p:AndroidNdkDirectory="C:\Android\android-sdk\ndk-bundle" /p:configuration="Release" /t:PackageForAndroid
