name: xamarin-android
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ASrunner
    steps:
      - run: git clone https://github.com/bbq-beets/asviridenko-test-repo.git .
      - run: |
          cd xamarin-android/vs2019/XamarinAndroidVS2019
          nuget restore XamarinAndroidVS2019.sln
          msbuild XamarinAndroidVS2019.csproj /p:AndroidNdkDirectory="C:\Android\android-sdk\ndk-bundle" /p:configuration="Release" /t:PackageForAndroid
